### ISSUE TITLE
Wont work for me.

### ISSUE THREAD

**Issue by xXSirGamesXx** [NL-4-DEVS/Pets#15]
SO I downloaded the plugin and it crashes every time. When I start server I get this error.
`[16:46:29] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[16:46:29] [Server thread/EMERGENCY]: Please upload the "C:\Users\xXSir\Downloads\BCN\crashdumps/CrashDump_Tue_May_2-16.46.29-ACT_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
`
I don't know the issue but.

**Comment by Driesboy** [comment]
can you upload the crashdump??

**Comment by Crypthu97** [comment]
Tesseract Crash Dump Thu May 4 15:27:45 BST 2017

Error: Class pets\PetCommand contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (pocketmine\command\Command::execute)
File: /plugins/Pets-master/src/pets/PetCommand
Line: 0
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN : Pets v2.0.0

Code:
[1] <?php
[2] 
[3] namespace pets;
[4] 
[5] use pocketmine\command\CommandSender;
[6] use pocketmine\command\Command;
[7] use pocketmine\command\PluginCommand;
[8] use pets\main;
[9] use pocketmine\utils\Config;
[10] use pocketmine\utils\TextFormat as TF;

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 107; API 3.0.1]
uname -a: Windows NT CRYPTHU 10.0 build 14393 (Windows 10) AMD64
PHP version: 7.0.17
Zend version: 3.0.0
OS : WINNT, win

Server uptime: 2 seconds
Number of loaded worlds: 4
Players online: 0/80

Loaded plugins:
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.1.0, 2.0.0
InvisibleLogin 1.1 by EvolSoft for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
MagicWE 0.3.0 by XenialDan for API(s) 2.0.0, 3.0.0
ManyWorlds 2.1.0 by aliuly for API(s) 2.0.0
Pets 2.0.0 by Driesboy for API(s) 2.0.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0,2.0.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0

**Comment by MalakasPlayzMC** [comment]
This works for MCPE 1.0.3: https://www.mediafire.com/file/1n5j484h9irephy/Pets_v1.5.0.phar

**Comment by Crypthu97** [comment]
MCPE 1.0.7 Windows 10 Edition :) no work downdate ( - update ) xd

**Comment by Driesboy** [comment]
i am trying to fix the plugin

**Comment by Crypthu97** [comment]
Entity bug :D

**Comment by Crypthu97** [comment]
Finish?

**Comment by Driesboy** [comment]
yep its fixed

**Comment by Crypthu97** [comment]
![image](https://cloud.githubusercontent.com/assets/27623343/25717797/ece6d26e-3103-11e7-8cf4-afce9704ae62.png)

Console: 
[Tesseract] [18:56:54] CRITICAL> Unhandled exception executing command 'pets spawn Dog' in pets: Class pets\EconomyAPI not found
[Tesseract] [18:56:54] CRITICAL> ClassNotFoundException: "Class pets\EconomyAPI not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by Crypthu97** [comment]
oh wait im no downloaded EnconomyAPI :D

**Comment by Crypthu97** [comment]
[Tesseract] [19:01:27] CRITICAL> Unhandled exception executing command 'pets spawn Dog' in pets: Class pets\EconomyAPI not found
[Tesseract] [19:01:27] CRITICAL> ClassNotFoundException: "Class pets\EconomyAPI not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
plugins
[Tesseract] [19:01:53] INFO> Plugins (13): DevTools v1.10.0, PurePerms v1.3.7, Broadcaster v1.16, #EconomyAPI v2.0.9, EssentialsPE v2.0.0, InvisibleLogin v1.1, iProtector v3.1b, MagicWE v0.3.0, ManyWorlds v2.1.0, Pets v2.0.0, ServerAuth v2.13, MyPlot v1, PureChat v1.4.0

**Comment by Crypthu97** [comment]
No works

**Comment by Crypthu97** [comment]
im added EconomyAPI :/

**Comment by Driesboy** [comment]
fixed if you dont have economyapi just remove the code for that

**Comment by Crypthu97** [comment]
Thank you <3
